#!/usr/bin/env bash

menu_main() {
  local choice

  while :; do
    if menu_nav_is_set; then
      case "$(menu_nav_value)" in
        main)
          menu_nav_clear
          ;;
        *)
          return 0
          ;;
      esac
    fi
    ui_header "Main Menu"

    ui_opt 1 "Enshrouded Server Settings"
    ui_opt 2 "Server Manager Settings"
    ui_opt 3 "Backups"
    ui_opt 4 "start"
    ui_opt 5 "stop"
    ui_opt 6 "restart"
    ui_opt 7 "update"
    ui_opt 8 "force-update"
    ui_opt 9 "password-view"
    ui_opt 10 "Create Savegame Backup (.zip)"
    ui_opt 11 "Other ctl Commands"
    echo

    ui_actions_bar "x Exit"
    echo
    choice="$(ui_prompt_choice "Choice")"
    choice="$(echo "$choice" | tr '[:upper:]' '[:lower:]' | xargs)"
    case "$choice" in
      1)
        menu_enshrouded_settings
        ;;
      2)
        menu_manager_settings
        ;;
      3)
        menu_backups_menu
        ;;
      4)
        menu_run_ctl start
        ;;
      5)
        menu_run_ctl stop
        ;;
      6)
        menu_run_ctl restart
        ;;
      7)
        menu_run_ctl update
        ;;
      8)
        menu_run_ctl force-update
        ;;
      9)
        menu_run_ctl password-view
        ;;
      10)
        menu_run_savegame_backup
        ;;
      11)
        menu_other_commands
        ;;
      0|x|q)
        ui_clear
        menu_nav_set "exit"
        return 0
        ;;
      *)
        ui_warn_line "Invalid selection."
        ui_pause
        ;;
    esac
  done
}
