#!/bin/bash
. "$(dirname "$0")/../shared/common"
. "$(dirname "$0")/../shared/profile"
. "$(dirname "$0")/../shared/env"
init_runtime_env

main() {
  verifyVariables
  createFolders
  applyPermissions
  setupSyslog
  exec /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
}

createFolders() {
  info "Creating server folders (save, logs, backup)"
  mkdir -p "$MANAGER_DATA_DIR" "$MANAGER_PROFILE_ROOT"

  if [[ -n "$ENSHROUDED_SAVE_DIR" ]]; then
    if [[ "$ENSHROUDED_SAVE_DIR" == /* ]]; then
      mkdir -p "$ENSHROUDED_SAVE_DIR"
    else
      mkdir -p "$install_path/$ENSHROUDED_SAVE_DIR"
    fi
  fi

  if [[ -n "$ENSHROUDED_LOG_DIR" ]]; then
    if [[ "$ENSHROUDED_LOG_DIR" == /* ]]; then
      mkdir -p "$ENSHROUDED_LOG_DIR"
    else
      mkdir -p "$install_path/$ENSHROUDED_LOG_DIR"
    fi
  fi

  if [[ -n "$BACKUP_CRON" ]] && [[ -n "$BACKUP_DIR" ]]; then
    if [[ "$BACKUP_DIR" == /* ]]; then
      mkdir -p "$BACKUP_DIR"
    else
      mkdir -p "$install_path/$BACKUP_DIR"
    fi
  fi
}

# Apply user id and group id
applyPermissions() {
  info "Setting uid:gid of enshrouded to $PUID:$PGID"
  groupmod -g "${PGID}" -o enshrouded
  usermod -u "${PUID}" -o enshrouded
  sed -i -E "s/^(enshrouded:x):[0-9]+:[0-9]+:(.*)/\\1:$PUID:$PGID:\\2/" /etc/passwd

  chown -R enshrouded:enshrouded \
    /home/enshrouded \
    /var/run/enshrouded

  if [[ -n "${MANAGER_DATA_DIR:-}" ]] && [[ "$MANAGER_DATA_DIR" == /* ]]; then
    chown -R enshrouded:enshrouded "$MANAGER_DATA_DIR"
  fi

  if [[ -n "${MANAGER_PROFILE_ROOT:-}" ]] && [[ "$MANAGER_PROFILE_ROOT" == /* ]]; then
    chown -R enshrouded:enshrouded "$MANAGER_PROFILE_ROOT"
  fi

  if [[ "$ENSHROUDED_SAVE_DIR" == /* ]]; then
    debug "Setting permissions for $ENSHROUDED_SAVE_DIR"
    chown -R enshrouded:enshrouded "$ENSHROUDED_SAVE_DIR"
  fi

  if [[ "$ENSHROUDED_LOG_DIR" == /* ]]; then
    debug "Setting permissions for $ENSHROUDED_LOG_DIR"
    chown -R enshrouded:enshrouded "$ENSHROUDED_LOG_DIR"
  fi

  if [[ "$BACKUP_DIR" == /* ]]; then
    debug "Setting permissions for $BACKUP_DIR"
    chown -R enshrouded:enshrouded "$BACKUP_DIR"
  fi

  chgrp enshrouded /etc/supervisor/supervisord.conf
}

# Configure syslog
setupSyslog() {
  info "Setting up syslogd - logging to stdout"

  cat >"$rsyslog_conf" <<EOF
\$FileOwner root
\$FileGroup root
\$PrivDropToUser root
\$PrivDropToGroup root

\$template custom,"%timegenerated:1:10:date-rfc3339% %timegenerated:12:23:date-rfc3339% %syslogtag%%msg:::sp-if-no-1st-sp%%msg:::drop-last-lf%\n"
\$ActionFileDefaultTemplate custom

:msg, contains, "[session] Pending packets list is full" stop
*.*;cron,auth,authpriv.none /proc/self/fd/1          # send everything to stdout
EOF

  cat >"$supervisor_syslog_conf" <<EOF
[program:rsyslogd]
user=root
environment=HOME="/root",USER="root",LANG="en_US.UTF-8",PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
command=/usr/sbin/rsyslogd -n
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autostart=true
autorestart=true
priority=10
EOF
}

verifyVariables() {
  verify_variables
}

main
