#!/bin/bash
. "$(dirname "$0")/common"
. "$(dirname "$0")/profile"
. "$(dirname "$0")/env"
init_runtime_env

main() {
  info "Stopping enshrouded server"
  supervisorctl stop enshrouded-server

  info "Reset enshrouded server roles"
  echo "$(jq 'del(.userGroups)' ${install_path}/enshrouded_server.json)" > ${install_path}/enshrouded_server.json

  info "Stop container for a clean start"
  kill -INT $(cat /var/run/supervisord.pid)
}

main
