#!/bin/bash
. "$(dirname "$0")/../../shared/common"
. "$(dirname "$0")/../../shared/profile"
. "$(dirname "$0")/../../shared/env"
init_runtime_env
. "$(dirname "$0")/../../shared/enshrouded-bootstrap-shared"

main() {
  info "Running enshrouded-bootstrap"
  prepareEnshroudedAppFolders
  updateOrCreateEnshroudedServerConfig
  prepareSteamA2sPythonLibrary

  # no proton bootstrap needed

  initCrontab
  bootstrapHook
  supervisorctl start enshrouded-updater
  info "Bootstrap complete"
}

main
